import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False, slow_mo=1000)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://www.saucedemo.com/")
    page.locator("[data-test=\"username\"]").click()
    page.locator("[data-test=\"username\"]").fill("standar_user")
    page.locator("[data-test=\"username\"]").press("Tab")
    page.locator("[data-test=\"password\"]").press("ArrowUp")
    page.locator("[data-test=\"username\"]").click()
    page.locator("[data-test=\"username\"]").click()
    page.locator("[data-test=\"username\"]").click()
    page.locator("[data-test=\"username\"]").click()
    page.locator("[data-test=\"username\"]").press("ArrowLeft")
    page.locator("[data-test=\"username\"]").press("ArrowLeft")
    page.locator("[data-test=\"username\"]").press("ArrowLeft")
    page.locator("[data-test=\"username\"]").press("ArrowLeft")
    page.locator("[data-test=\"username\"]").press("ArrowLeft")
    page.locator("[data-test=\"username\"]").press("ArrowLeft")
    page.locator("[data-test=\"username\"]").press("ArrowRight")
    page.locator("[data-test=\"username\"]").press("ArrowDown")
    page.locator("[data-test=\"username\"]").press("ArrowLeft")
    page.locator("[data-test=\"username\"]").press("ArrowLeft")
    page.locator("[data-test=\"username\"]").press("Tab")
    page.locator("[data-test=\"password\"]").fill("secret_sauce")
    page.locator("[data-test=\"login-button\"]").click()
    page.locator("[data-test=\"username\"]").click()
    page.locator("[data-test=\"username\"]").press("ArrowLeft")
    page.locator("[data-test=\"username\"]").press("ArrowLeft")
    page.locator("[data-test=\"username\"]").press("ArrowLeft")
    page.locator("[data-test=\"username\"]").press("ArrowLeft")
    page.locator("[data-test=\"username\"]").press("ArrowLeft")
    page.locator("[data-test=\"username\"]").press("ArrowLeft")
    page.locator("[data-test=\"username\"]").press("ArrowRight")
    page.locator("[data-test=\"username\"]").fill("standard_user")
    page.locator("[data-test=\"login-button\"]").click()
    page.locator("[data-test=\"add-to-cart-sauce-labs-backpack\"]").click()
    page.locator("[data-test=\"add-to-cart-sauce-labs-bolt-t-shirt\"]").click()
    page.locator("[data-test=\"add-to-cart-sauce-labs-bike-light\"]").click()
    page.locator("[data-test=\"add-to-cart-sauce-labs-fleece-jacket\"]").click()
    page.locator("[data-test=\"shopping-cart-link\"]").click()
    page.locator("[data-test=\"remove-sauce-labs-backpack\"]").click()
    page.locator("[data-test=\"remove-sauce-labs-bolt-t-shirt\"]").click()
    page.locator("[data-test=\"remove-sauce-labs-bike-light\"]").click()
    page.locator("[data-test=\"remove-sauce-labs-fleece-jacket\"]").click()
    page.locator("[data-test=\"continue-shopping\"]").click()
    page.locator("div").filter(has_text="Swag Labs").nth(5).click()
    page.locator("[data-test=\"about-sidebar-link\"]").click()
    page.goto("https://www.saucedemo.com/inventory.html")
    page.locator("div").filter(has_text="Swag Labs").nth(5).click()
    page.locator("[data-test=\"product-sort-container\"]").select_option("za")
    page.get_by_role("button", name="Close Menu").click()
    page.locator("[data-test=\"product-sort-container\"]").select_option("lohi")
    page.locator("[data-test=\"product-sort-container\"]").select_option("hilo")
    page.locator("[data-test=\"shopping-cart-link\"]").click()
    page.locator("[data-test=\"continue-shopping\"]").click()
    page.locator("[data-test=\"add-to-cart-sauce-labs-backpack\"]").click()
    page.locator("[data-test=\"add-to-cart-sauce-labs-bike-light\"]").click()
    page.locator("[data-test=\"shopping-cart-link\"]").click()
    page.locator("[data-test=\"checkout\"]").click()
    page.locator("[data-test=\"firstName\"]").click()
    page.locator("[data-test=\"firstName\"]").fill("abhi")
    page.locator("[data-test=\"firstName\"]").press("Tab")
    page.locator("[data-test=\"lastName\"]").fill("manyu")
    page.locator("[data-test=\"postalCode\"]").click()
    page.locator("[data-test=\"postalCode\"]").fill("313020")
    page.locator("[data-test=\"continue\"]").click()
    page.locator("[data-test=\"payment-info-value\"]").click()
    page.locator("[data-test=\"shipping-info-value\"]").click()
    page.locator("[data-test=\"total-info-label\"]").click()
    page.locator("[data-test=\"finish\"]").click()
    page.locator("[data-test=\"back-to-products\"]").click()
    page.get_by_role("button", name="Open Menu").click()
    page.locator("[data-test=\"logout-sidebar-link\"]").click()
    page.pause()
    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
